version: "3"

networks:
  internal:
    driver: bridge
#    ipam:
#      driver: default
#      config:
#        - subnet: 192.168.220.0/28

#volumes:

services:
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    container_name: dev_mysql
    restart: always
    tty: true
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./volumes/mysql:/var/lib/mysql
      - ./logs/mysql:/var/logs/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    logging:
      driver: "json-file"
      options:
        max-size: "1024k"
        max-file: "5"
    networks:
      - internal

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
      args:
        - APP_DIR=${CONTAINER_PROJECTS_DIR}
        - USER_ID=${PHP_USER_ID}
        - USER_NAME=${PHP_USER_NAME}
        - USER_GROUP_ID=${PHP_GROUP_ID}
        - USER_GROUP_NAME=${PHP_GROUP_NAME}
    container_name: dev_nginx
    restart: always
    tty: true
    depends_on:
      - php-fpm
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/hosts:/etc/nginx/hosts
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./logs/nginx:/var/logs/nginx
      - ${LOCAL_PROJECTS_DIR}:${CONTAINER_PROJECTS_DIR}
    ports:
      - "${NGINX_PORT}:80"
      - "${NGINX_SSL_PORT}:443"
    logging:
      driver: "json-file"
      options:
        max-size: "1024k"
        max-file: "5"
    networks:
      - internal

  php-fpm:
    build:
      context: ./php-fpm/${PHP_VERSION}
      dockerfile: Dockerfile
      args:
        - DEV_ENV=${DEV_ENV}
        - APP_DIR=${CONTAINER_PROJECTS_DIR}
        - USER_ID=${PHP_USER_ID}
        - USER_NAME=${PHP_USER_NAME}
        - USER_GROUP_ID=${PHP_GROUP_ID}
        - USER_GROUP_NAME=${PHP_GROUP_NAME}
    container_name: "${DEV_ENV_PREFIX}_php_fpm"
    restart: always
    tty: true
    depends_on:
      - mysql
    volumes:
      - ${LOCAL_PROJECTS_DIR}:${CONTAINER_PROJECTS_DIR}
      - ./php-fpm/${PHP_VERSION}/www.conf:/usr/local/etc/php-fpm.d/www.conf
    ports:
      - "${PHP_XDEBUG_PORT}:9000"
    logging:
      driver: "json-file"
      options:
        max-size: "1024k"
        max-file: "3"
    networks:
      - internal

  mongo:
    image: mongo
    container_name: dev_mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "${MONGODB_PORT}:27017"
    logging:
      driver: "json-file"
      options:
        max-size: "1024k"
        max-file: "1"
    networks:
      - internal

  mongo-express:
    image: mongo-express
    container_name: dev_mongo_express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${ME_CONFIG_MONGODB_ADMINUSERNAME}:${ME_CONFIG_MONGODB_ADMINPASSWORD}@dev_mongodb:${MONGODB_PORT}/
    ports:
      - "${MONGO_EXPRESS_PORT}:8081"
    logging:
      driver: "json-file"
      options:
        max-size: "1024k"
        max-file: "1"
    networks:
      - internal

  memcached:
    container_name: dev_memcached
    image: memcached:latest
    entrypoint:
      - memcached
      - -m 1024
    depends_on:
      - nginx
    ports:
      - "${MEMCACHED_PORT}:11211"
    networks:
      - internal

  rabbitmq:
    container_name: dev_rabbitmq
    image: rabbitmq:3.8-management-alpine
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    depends_on:
      - php-fpm
    volumes:
      - ./volumes/rabbitmq/:/var/lib/rabbitmq/
      - ./logs/rabbitmq/:/var/log/rabbitmq/log
    ports:
      - "${RABBITMQ_PORT_1}:5672"
      - "${RABBITMQ_PORT_2}:15672"
    networks:
      - internal